# Generated by Django 5.0.4 on 2024-04-13 12:13

import django.db.models.deletion
import prose.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', prose.fields.DocumentContentField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerpt', prose.fields.RichTextField()),
                ('kommune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.kommune')),
                ('body', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.articlecontent')),
            ],
        ),
    ]
