# Generated by Django 5.0.4 on 2024-04-13 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkdownContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('kommune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.kommune')),
            ],
            options={
                'verbose_name_plural': 'Markdown content',
            },
        ),
    ]
