# Generated by Django 5.0.4 on 2024-04-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0002_articlecontent_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
    ]
