# Generated by Django 5.0.4 on 2024-04-14 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0003_emissiondata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emissiondata',
            name='kommune',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.kommune'),
        ),
    ]
