# Generated by Django 5.0.4 on 2024-05-21 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0004_alter_emissiondata_kommune'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('kommune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.kommune')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.actionfield')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.actionsource')),
            ],
        ),
    ]
