# Generated by Django 5.0.4 on 2024-04-13 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0004_markdowncontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='kommune',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.kommune'),
            preserve_default=False,
        ),
    ]
