# Generated by Django 5.0.4 on 2024-05-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0005_actionfield_actionsource_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='short_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
