# Generated by Django 5.0.4 on 2024-06-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0006_action_short_title_action_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('unbekannt', 'Unbekannt'), ('nicht begonnen', 'Nicht Begonnen'), ('begonnen', 'Begonnen'), ('teilweise umgesetzt', 'Teilweise Umgesetzt'), ('umgesetzt', 'Umgesetzt'), ('verschoben', 'Verschoben')], default='unbekannt', max_length=50),
        ),
    ]
