# Generated by Django 5.0.4 on 2024-07-01 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0008_actionfield_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.TextField()),
                ('old_status', models.CharField(choices=[('unbekannt', 'Unbekannt'), ('nicht begonnen', 'Nicht Begonnen'), ('begonnen', 'Begonnen'), ('teilweise umgesetzt', 'Teilweise Umgesetzt'), ('umgesetzt', 'Umgesetzt'), ('verschoben', 'Verschoben')], max_length=50)),
                ('new_status', models.CharField(choices=[('unbekannt', 'Unbekannt'), ('nicht begonnen', 'Nicht Begonnen'), ('begonnen', 'Begonnen'), ('teilweise umgesetzt', 'Teilweise Umgesetzt'), ('umgesetzt', 'Umgesetzt'), ('verschoben', 'Verschoben')], max_length=50)),
                ('date', models.DateField()),
                ('user', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=1000, null=True)),
                ('source_is_link', models.BooleanField(default=False)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.action')),
            ],
        ),
    ]
