# Generated by Django 5.0.4 on 2024-07-01 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0009_actionprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionprogress',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
