# Generated by Django 5.0.4 on 2024-07-06 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klimawatch_app', '0010_actionprogress_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='KommuneActionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.actionfield')),
                ('kommune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='klimawatch_app.kommune')),
            ],
        ),
    ]
